name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build and Publish Docker image
        uses: DrSkunk/gp-docker-action@1.1.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: grc-install
          image-tag: latest